name: "Build kernels"

env:
  CONFIGURATION: "repos.json"
  OUT_DIR: "out"

on:
  workflow_dispatch:

jobs:
  Set-repos:
    name: "üêÇ Parse repos.json"
    runs-on: ubuntu-latest
    outputs:
      repos: ${{ steps.generate-matrix.outputs.repos }}
    steps:
      - name: "üòÑ Checkout"
        uses: actions/checkout@v3

      - name: "üòÜ Generate Matrix"
        id: generate-matrix
        run: |
          echo "repos<<EOF" >> $GITHUB_OUTPUT
          cat  ${{ env.CONFIGURATION }} >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

  Build-Kernel:
    name: "üêé Build kernel"
    runs-on: ubuntu-latest
    needs:
      - Set-repos
    strategy:
      max-parallel: 2
      fail-fast: false
      matrix:
        repos: ${{ fromJSON(needs.Set-repos.outputs.repos) }}
    env:
      kernelDir: ${{ matrix.repos.kernelSource.name }}_${{ matrix.repos.kernelSource.device }}

      kernelName: ${{ matrix.repos.kernelSource.name }}
      kernelRepo: ${{ matrix.repos.kernelSource.repo }}
      kernelBranch: ${{ matrix.repos.kernelSource.branch }}
      kernelDevice: ${{ matrix.repos.kernelSource.device }}

      DEFCONFIG_NAME: ${{ matrix.repos.kernelSource.device }}_defconfig

      withKernelSU: ${{ matrix.repos.withKernelSU }}
    steps:
      - name: "‚ú® Create working dir"
        run: mkdir -p $kernelDir

      - name: "‚≠ê Install prerequisites"
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential bc curl git zip ftp gcc-aarch64-linux-gnu gcc-arm-linux-gnueabi libssl-dev lftp zstd wget libfl-dev python3 libarchive-tools

      - name: "üåü Clone kernel source => (${{ env.kernelRepo }})"
        working-directory: ./${{ env.kernelDir }}
        run: |
          git clone --recursive --branch $kernelBranch $kernelRepo $kernelName --depth=1

      - name: "üí´ Get toolchains"
        working-directory: ./${{ env.kernelDir }}
        env:
          toolchains: "${{ toJSON(matrix.repos.toolchains) }}"
        run: |
          toolchains_num="$(echo $toolchains | jq 'length')"
          echo $toolchains_num
          for ((i=0;i<toolchains_num;i++)); do
            name=$(echo $toolchains | jq -r ".[$i].name")
            repo=$(echo $toolchains | jq -r ".[$i].repo")
            branch=$(echo $toolchains | jq -r ".[$i].branch")
            git clone --recursive --branch $branch $repo $name --depth=1
            echo "$(pwd)/$name/" >> $GITHUB_PATH
            echo "$(pwd)/$name/bin" >> $GITHUB_PATH
          done

          echo "PATH Variable: $PATH"

      - name: "üòé Set args"
        id: generate-args
        working-directory: ./${{ env.kernelDir }}
        env:
          params: "${{ toJSON(matrix.repos.params) }}"
        run: |
          ARCH=$(echo $params | jq -r ".ARCH")
          echo "ARCH=$ARCH" >> $GITHUB_ENV
          
          args="-j$(nproc --all)"
          if [ -n "${{ env.OUT_DIR }}" ]; then
            mkdir -p $(pwd)/${{ env.OUT_DIR }}
            args="$args O=$(pwd)/${{ env.OUT_DIR }}"
          fi
          
          CC_VAL=$(echo $params | jq -r ".CC")
          if [ "$CC_VAL" = "clang" ]; then
            # Argumentos otimizados para Clang (sem NM/OBJCOPY para evitar Broken Pipe)
            args="$args CC=clang \
                  HOSTCC=clang \
                  CLANG_TRIPLE=$(echo $params | jq -r ".CLANG_TRIPLE") \
                  CROSS_COMPILE=$(echo $params | jq -r ".CROSS_COMPILE") \
                  CROSS_COMPILE_ARM32=$(echo $params | jq -r ".CROSS_COMPILE_COMPAT")"
          else
            # Argumentos padr√£o para GCC
            args="$args ARCH=$ARCH \
                  CROSS_COMPILE=$(echo $params | jq -r ".CROSS_COMPILE") \
                  CROSS_COMPILE_ARM32=$(echo $params | jq -r ".CROSS_COMPILE_COMPAT")"
          fi
          
          echo "args=$args" >> $GITHUB_OUTPUT

      - name: "üòã Install ReSukiSU"
        working-directory: ./${{ env.kernelDir }}/${{ env.kernelName }}
        if: ${{ env.withKernelSU == 'true' }}
        run: |
          mkdir -p include/linux/
          touch include/linux/seccomp_types.h

          # 1. Instala√ß√£o (Comando original)
          curl -LSs "https://raw.githubusercontent.com/ReSukiSU/ReSukiSU/main/kernel/setup.sh" | bash

          # 2. Patches de Compatibilidade (Seus comandos originais)
          sed -i 's/$(error TP hooks/\# $(error TP hooks/g' drivers/kernelsu/Kbuild
          
          if [ -f "drivers/kernelsu/app_profile.c" ]; then
            sed -i 's/atomic_set(&.*seccomp.filter_count, 0);/\/\/ atomic_set(...);/g' drivers/kernelsu/app_profile.c
          fi

          grep -rli 'strncpy_from_user_nofault' drivers/kernelsu/ | xargs -i@ sed -i 's/strncpy_from_user_nofault/strncpy_from_user/g' @
          grep -rli 'copy_from_user_nofault' drivers/kernelsu/ | xargs -i@ sed -i 's/copy_from_user_nofault/copy_from_user/g' @
          grep -rli 'copy_to_user_nofault' drivers/kernelsu/ | xargs -i@ sed -i 's/copy_to_user_nofault/copy_to_user/g' @

          # --- 1. Tuning de Resposta (DVFSP) ---

          sed -i 's/little-rise-time = <1000>/little-rise-time = <400>/g' arch/arm64/boot/dts/mediatek/mt6765.dts
          sed -i 's/big-rise-time = <1000>/big-rise-time = <400>/g' arch/arm64/boot/dts/mediatek/mt6765.dts
          sed -i 's/little-down-time = <750>/little-down-time = <1200>/g' arch/arm64/boot/dts/mediatek/mt6765.dts
          sed -i 's/big-down-time = <750>/big-down-time = <1200>/g' arch/arm64/boot/dts/mediatek/mt6765.dts
          sed -i 's/opp-microvolt = <600000>/opp-microvolt = <650000>/g' arch/arm64/boot/dts/mediatek/mt6765.dts
          sed -i 's/entry-latency-us = <600>/entry-latency-us = <350>/g' arch/arm64/boot/dts/mediatek/mt6765.dts
          sed -i 's/exit-latency-us = <600>/exit-latency-us = <350>/g' arch/arm64/boot/dts/mediatek/mt6765.dts
          sed -i 's/min-residency-us = <1200>/min-residency-us = <500>/g' arch/arm64/boot/dts/mediatek/mt6765.dts
          sed -i 's/opp-hz = /bits/ 64 <300000000>/opp-hz = /bits/ 64 <459000000>/g' arch/arm64/boot/dts/mediatek/mt6765.dts
          sed -i 's/entry-latency-us = <800>/entry-latency-us = <400>/g' arch/arm64/boot/dts/mediatek/mt6765.dts
          sed -i 's/exit-latency-us = <1000>/exit-latency-us = <500>/g' arch/arm64/boot/dts/mediatek/mt6765.dts
          sed -i 's/min-residency-us = <2000>/min-residency-us = <900>/g' arch/arm64/boot/dts/mediatek/mt6765.dts
          sed -i 's/capacity-dmips-mhz = <1024>/capacity-dmips-mhz = <1048>/g' arch/arm64/boot/dts/mediatek/mt6765.dts
          sed -i 's/capacity-dmips-mhz = <801>/capacity-dmips-mhz = <850>/g' arch/arm64/boot/dts/mediatek/mt6765.dts
          
          # --- 4. Defconfig Minimalista (Root + Fluidez) ---
          {
            # Depend√™ncias Obrigat√≥rias do ReSukiSU/KSU
            echo "CONFIG_KSU=y"
            echo "CONFIG_KALLSYMS=y"
            echo "CONFIG_KALLSYMS_ALL=y"
            echo "CONFIG_TMPFS_XATTR=y"
            
            # Core de Performance (O que realmente muda o celular)
            echo "CONFIG_HZ_450=y"
            echo "CONFIG_HZ=450"
            echo "CONFIG_CC_OPTIMIZE_FOR_PERFORMANCE=y"
            echo "CONFIG_WQ_POWER_EFFICIENT_DEFAULT=n"
            echo "CONFIG_CPU_FREQ_DEFAULT_GOV_PERFORMANCE=y"
            echo "CONFIG_CPU_FREQ_GOV_PERFORMANCE=y"
            echo "CONFIG_PREEMPT_COUNT=y"
            echo "CONFIG_SCHED_AUTOGROUP=y"
            echo "CONFIG_SCHED_WALT=y"
            echo "CONFIG_SCHED_TUNE=y"
            echo "CONFIG_DEFAULT_USE_ENERGY_AWARE=y"
            echo "CONFIG_SCHED_CORE_CTL=y"
            echo "CONFIG_HUGETLBFS=y"
            echo "CONFIG_HUGETLB_PAGE=y"
            echo "CONFIG_SCHEDSTATS=n"
            echo "CONFIG_DEBUG_KMEMLEAK=n"
            echo "CONFIG_SLUB_DEBUG=n"
            echo "CONFIG_PROFILING=n"
            echo "CONFIG_PROCESS_RECLAIM=y"
            echo "CONFIG_ADVISE_SYSCALLS=y"
            echo "CONFIG_DEVFREQ_GOV_PERFORMANCE=y"
            echo "CONFIG_ARM_MTK_BW_LEVEL=y"
           
            # I/O e RAM (Para abrir apps r√°pido e n√£o fechar os de fundo)
            echo "CONFIG_MQ_IOSCHED_DEADLINE=y"
            echo "CONFIG_DEFAULT_IOSCHED=\"mq-deadline\""
            echo "CONFIG_ZSMALLOC=y"
            echo "CONFIG_PGTABLE_MAPPING=y"

            # MediaTek Gaming/UI Boost
            echo "CONFIG_CPU_IDLE_GOV_TEO=y"
            echo "CONFIG_IRQ_TIME_ACCOUNTING=y"
            echo "CONFIG_MTK_DRAMC_LOW_POWER_REDUCE=n"
            echo "CONFIG_MTK_FPSGO_V3=y"
            echo "CONFIG_MTK_GPU_COMMON_DVFS_SUPPORT=y"
            echo "CONFIG_MTK_BOOST_GPU_FREQ=y"
            echo "CONFIG_MTK_MONITOR_CHIPS_Gpu=y"
            echo "CONFIG_RELR=y"
          } >> ./arch/${{ env.ARCH }}/configs/${{ env.DEFCONFIG_NAME }}

          # --- CORRE√á√ÉO DE ERROS DE COMPILA√á√ÉO ---
          # 1. Ignora declara√ß√µes impl√≠citas (corrige o erro cpu_util_rt)
          sed -i 's/-Werror=implicit-function-declaration/-Wno-error=implicit-function-declaration/g' Makefile
          
          # 2. Transforma avisos em alertas simples na pasta do agendador
          find kernel/sched/ -name "Makefile" | xargs sed -i 's/-Werror/-Wno-error/g'
          
      - name: "üëç Make defconfig"
        working-directory: ./${{ env.kernelDir }}/${{ env.kernelName }}
        env:
          args: ${{ steps.generate-args.outputs.args }}
          JOURNEY_BUILD_SCRIPT: "yes"
        run: |
          echo "PATH Variable: $PATH"
          make ${{ env.args }} ${{ env.DEFCONFIG_NAME }}

      - name: "üé∂ Build kernel"
        working-directory: ./${{ env.kernelDir }}/${{ env.kernelName }}
        env:
          args: ${{ steps.generate-args.outputs.args }}
          KBUILD_BUILD_USER: "g4bri3ldll"
          KBUILD_BUILD_HOST: "ReSukiSU-Lab"
          JOURNEY_BUILD_SCRIPT: "yes"
        run: |
          # Remove o sufixo -dirty para o nome ficar limpo
          export LOCALVERSION=""
          
          echo "PATH Variable: $PATH"
          # Comando de build com os argumentos do Clang/GCC + seu nome
          make ${args} ARCH=${{ env.ARCH }}

      - name: "üíõ Upload Image"
        uses: actions/upload-artifact@v4
        with:
          name: Image(${{ env.kernelDevice }}-${{ env.kernelName }}-${{ env.kernelBranch }})
          path: ./${{ env.kernelDir }}/${{ env.OUT_DIR }}/arch/${{ env.ARCH }}/boot/Image
          if-no-files-found: ignore
          retention-days: 7

      - name: "üíô Upload Image.gz"
        uses: actions/upload-artifact@v4
        with:
          name: Image.gz(${{ env.kernelDevice }}-${{ env.kernelName }}-${{ env.kernelBranch }})
          path: ./${{ env.kernelDir }}/${{ env.OUT_DIR }}/arch/${{ env.ARCH }}/boot/Image.gz
          if-no-files-found: ignore
          retention-days: 7

      - name: "üíú Upload dtb"
        uses: actions/upload-artifact@v4
        with:
          name: dtb(${{ env.kernelDevice }}-${{ env.kernelName }}-${{ env.kernelBranch }})
          path: ./${{ env.kernelDir }}/${{ env.OUT_DIR }}/arch/${{ env.ARCH }}/boot/dts/mediatek/*.dtb
          if-no-files-found: warn
          retention-days: 7

      - name: "‚ù§Ô∏è Upload dtbo.img"
        uses: actions/upload-artifact@v4
        with:
          name: dtbo.img(${{ env.kernelDevice }}-${{ env.kernelName }}-${{ env.kernelBranch }})
          path: ./${{ env.kernelDir }}/${{ env.OUT_DIR }}/arch/${{ env.ARCH }}/boot/dtbo.img
          if-no-files-found: ignore
          retention-days: 7
